### ISSUE TITLE
Secure the website

### ISSUE THREAD

**Issue by WaldaKeza** [AlexTelon/FlexiCharge-My-pages#116]
So you cann't get access to the pages that you do not have access to.

For example from login to profile through URL

**Comment by GabrielAdward** [comment]
Reproduce issue:
1. Visit the Sign-in page: (http://localhost:3000/sign-in)
2. Change the URL from [](http://localhost:3000/sign-in) to [](http://localhost:3000/profile)

Expected output:
If a user is not logged in, they should not have access to the profile page. If they attempt to access it by modifying the URL, they should be automatically redirected to the sign-in page.
