### ISSUE TITLE
Restructure folders

### ISSUE THREAD

**Issue by GabrielAdward** [AlexTelon/FlexiCharge-My-pages#120]
The folder structure should follow a specific pattern. 
Change the folder structure according to the image below. This will create a separation of concern and increase readability while also decreasing search time.

Image:
![Skärmbild 2023-09-12 131354](https://github.com/AlexTelon/FlexiCharge-My-pages/assets/98411685/a4c5196d-ee4f-4318-a8dd-9ccaabf27535)

**Comment by Nvcxlx** [comment]
Structure before: 
![image](https://github.com/AlexTelon/FlexiCharge-My-pages/assets/140490220/80b30bb8-8cbf-46ba-abd7-14f5ad182abe)

**Comment by Nvcxlx** [comment]
Structure after: 
![image](https://github.com/AlexTelon/FlexiCharge-My-pages/assets/140490220/514f6043-3000-4477-90f8-6de5d290ea53)

The structure is now as follows:
- assets (logos, etc.)
- components -> divided into the folders **invoiceTab**, **profileTab** and **styles**, as well as the files **"AuthService"** and generally **"Tabs"**.
- pages
- test
- theme and
- utils -> divided into **fonts** and everything that has something to do with **validation**.

I hope this is a bit clearer now.
