### ISSUE TITLE
Table Design

### ISSUE THREAD

**Issue by Nvcxlx** [AlexTelon/FlexiCharge-My-pages#158]
**Describe the solution you'd like**
The tables should look as follows:

- bold column headers
- light grey header background
- just row lines, no column lines
- if there are buttons, they should be green with white text
- white background

**Additional context**

![PXL_20230928_121008429](https://github.com/AlexTelon/FlexiCharge-My-pages/assets/140490220/72fbc615-f9f5-4025-b39f-4550673ab79f)

**Comment by flrn579** [comment]
I don't think this issue or the branch for this issue still needs to get merged. The new design of the table is already implemented in the other branch "149-filter-for-charging-history", because the table file changed a lot
